### ISSUE TITLE
Feature Request: Additional options

### ISSUE THREAD

**Issue by kyuubi08** [HealthITAU/TED#4]
Would it be possible to add more options, such as uptime, ip address, etc or would it be easier to try to do the token on our own?

**Comment by Yoshify** [comment]
Hi Kyuubi,

Tokens like this are entirely possible but would only draw from the time TED was ran. TED doesn't continue running - it draws once, then closes. For live information like uptime, etc., TED would need to continue running and either redraw at a fixed interval or hook Windows events (like desktop refreshes) and redraw then. This isn't something planned for the time being but you're more than welcome to take a crack at it and submit a PR.

If you have any ideas for static tokens you'd like to see, feel free to suggest them or make a PR!
